config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'articles/generate/:count' => 'articles#generate'

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  searchable do
    text :title, :abstract
    text :content, stored: true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def generate
    require 'open-uri'
    # clean_articles
    generate_articles(params[:count].to_i)
    redirect_to root_path
  end

  # GET /articles
  # GET /articles.json
  def index
    # search_key = "%#{params[:search]}%"
    # @articles = Article.where('title like :criteria or abstract like :criteria or content like :criteria',criteria: search_key).to_a

    @articles = Article.search do
      fulltext params[:search] do
        fields (:title)
        fields (:abstract)
        fields (:content)
        highlight :content
      end
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :abstract, :content)
    end


    def generate_articles(count)
      count.times do
        rnd_article = Nokogiri::HTML(open("http://pdos.csail.mit.edu/cgi-bin/sciredirect.cgi"))
        # rnd_article = Nokogiri::HTML(open("http://scigen.csail.mit.edu/scicache/870/scimakelatex.23796.none.html"))
        title = rnd_article.css('h1')[0].text.squish
        abstract = rnd_article.css('div.p')[2].next.text.squish
        content = (rnd_article.css('br')[4].next.text + rnd_article.css('br')[5].next.text + rnd_article.css('br')[6].next.text).squish
        Article.new(title: title, abstract: abstract, content: content).save!
      end
    end

    def clean_articles
      Article.delete_all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag articles_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<h1>Listing Articles</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Abstract</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each_hit_with_result do |hit,article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.abstract %></td>
        <td>
          <% content = article.content %>
          <% hit.highlights(:content).each do |highlight| %>
            <% partial_original = highlight.format { |word| word } %>
            <% partial_formatted = highlight.format { |word| "<span class='highlight'>#{word}</span>" } %>
            <% content = content.gsub(partial_original,partial_formatted).html_safe %>
          <% end %>
          <%= content %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @article.abstract %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>